version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    tty: true
    stdin_open: true
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
      - celery-beat

  celery:
    build: .
    container_name: celery_worker
    command: celery -A examen worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A examen beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
